{
 "title": "GPU load",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(gpumon_engine_usage,node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (engine) (gpumon_engine_usage{attrib=\"busy\", node=~\"^$node$\"})",
     "legendFormat": "{{engine}}"
    }
   ]
  },
  {
   "title": "clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum (gpumon_clients_count{node=~\"^$node$\"})",
     "legendFormat": "clients"
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum by (type) (gpumon_power{node=~\"^$node$\"})",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}